// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class TblProductDetail
{
    public int ProductDetailId { get; set; }

    public string SerialNumber { get; set; }

    public int ProductId { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }
    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<LkpProductDetailsAttribute> LkpProductDetailsAttributes { get; set; } = new List<LkpProductDetailsAttribute>();

    public virtual TblProduct Product { get; set; }

    public virtual TblInventory Inventory { get; set; }
}